spring.application.name=event-mate

# Server Configuration
server.port=8080

# Logging Configuration
logging.level.root=INFO
logging.level.com.hemanthjangam.event_mate=DEBUG

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configuration
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Gemini AI Configuration
# REPLACE WITH YOUR ACTUAL KEY
gemini.api.key=YOUR_GEMINI_API_KEY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent

# Stripe Configuration
# REPLACE WITH YOUR ACTUAL KEY
stripe.secret.key=YOUR_STRIPE_SECRET_KEY

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# REPLACE WITH YOUR ACTUAL CREDENTIALS
spring.mail.username=hemanthjangam.edu@gmail.com
spring.mail.password=xjbktkdxbfusncco
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
